### ISSUE TITLE
Deprecation notice

### ISSUE THREAD

**Issue by OriginalEXE** [mapsiter/chrome-syntax#1]
Hello,

first of all, thanks for this great theme :)

There is a deprecation notice as of 1.13.0 related to the theme, seems like some selectors have been changed. Any chance you could update the theme? It still works, but would be great to get rid of the notice.

Thanks

**Comment by mapsiter** [comment]
Re,

Thanks for pointing this out! The theme is now updated.
Please let me know in case of any issues arise. 

Thank you

**Comment by OriginalEXE** [comment]
Hello,

thank you for the update :)

I updated the theme and noticed that some notices are gone, but some still remain:

In `chrome-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.syntax--keyword.operator` => `.syntax--keyword.syntax--operator`

* `.syntax--source.syntax--css .syntax--constant.syntax--other.syntax--color,
.syntax--source.syntax--css .syntax--constant.syntax--other.rgb-value` => `.syntax--source.syntax--css .syntax--constant.syntax--other.syntax--color,
.syntax--source.syntax--css .syntax--constant.syntax--other.syntax--rgb-value`

* `.syntax--source.syntax--css .syntax--constant.syntax--other.syntax--color.syntax--scss .syntax--punctuation.syntax--definition,
.syntax--source.syntax--css .syntax--constant.syntax--other.rgb-value.syntax--scss .syntax--punctuation.syntax--definition` => `.syntax--source.syntax--css .syntax--constant.syntax--other.syntax--color.syntax--scss .syntax--punctuation.syntax--definition,
.syntax--source.syntax--css .syntax--constant.syntax--other.syntax--rgb-value.syntax--scss .syntax--punctuation.syntax--definition`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by mapsiter** [comment]
Hmm.. that's pretty weird, I can remember updating these selectors, too. :)
Let me have an other look..

**Comment by mapsiter** [comment]
Please make sure you have the latest, v0.5.4 of the theme installed as I've missed to update a couple of the above selectors in my first updates. It means you should have received not only one but a couple of updates. Your issue could exist because you updated the theme only once before my final update.

**Comment by OriginalEXE** [comment]
Hi,

you are right, for some reason it only updated to 0.5.3, I would assume Atom would update it immediately to the latest available version.

Thanks again for this, works great now, and I love the look :)

Cheers!
